file(MAKE_DIRECTORY "${WORK_DIR}")
file(REMOVE "${WORK_DIR}/exit-output.txt")
execute_process(COMMAND "${PROGRAM}" "${MODE}"
  WORKING_DIRECTORY "${WORK_DIR}"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error
  TIMEOUT 15)
if(NOT "${result}" STREQUAL "${EXPECTED_EXIT}")
  message(FATAL_ERROR "Unexpected exit: ${result}; expected ${EXPECTED_EXIT}\n${output}\n${error}")
endif()
if(MODE STREQUAL "short" OR MODE STREQUAL "long")
  string(STRIP "${error}" error)
  if(NOT error STREQUAL "Topdrawer FDATE requires a 24-character result buffer." OR NOT output STREQUAL "")
    message(FATAL_ERROR "Expected only the FDATE length diagnostic:\n${output}\n${error}")
  endif()
else()
  if(NOT error STREQUAL "")
    message(FATAL_ERROR "Unexpected diagnostic (including sanitizer failures): ${error}")
  endif()
  if(MODE STREQUAL "datetime")
    string(STRIP "${output}" output)
    if(NOT output STREQUAL "DATETIME_OK")
      message(FATAL_ERROR "Missing successful datetime result: ${output}")
    endif()
  else()
    if(NOT EXISTS "${WORK_DIR}/exit-output.txt")
      message(FATAL_ERROR "EXIT did not preserve pending output")
    endif()
    file(READ "${WORK_DIR}/exit-output.txt" contents)
    if(NOT contents STREQUAL "output before exit\n")
      message(FATAL_ERROR "EXIT output was not flushed correctly: ${contents}")
    endif()
  endif()
endif()
